version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: weblog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: weblog
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - weblog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: weblog-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - weblog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    image: openjdk:11
    container_name: weblog-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: weblog
    ports:
      - "8080:8080"
    volumes:
      - ../weblog/weblog-springboot/weblog-web/target/weblog-web-0.0.1-SNAPSHOT.jar:/app/weblog-web-0.0.1-SNAPSHOT.jar:ro
      - ./logs:/app/logs
    working_dir: /app
    command: ["java", "-Dspring.profiles.active=docker", "-Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver", "-jar", "weblog-web-0.0.1-SNAPSHOT.jar"]
    networks:
      - weblog-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  # Vue.js Frontend (served by Nginx)
  frontend:
    image: nginx:alpine
    container_name: weblog-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "5173:80"  # Alternative port for development
    volumes:
      - ../blog-vue3/dist:/usr/share/nginx/html:ro
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - weblog-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  weblog-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local